name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy via AWS Systems Manager
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.AWS_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["su - ubuntu -c \"cd ~/app/Resume-Saathi/Backend && git pull origin main && docker compose up --build -d\""]' \
            --output text
            
          echo "Deployment command sent successfully to the server!"
